# .github/workflows/auto-version.yml
# Resources: https://github.com/marketplace/actions/git-semantic-version#git-based-semantic-versioning
# Auto-generates version for commits

name: Auto Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Generate Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          # Add any other needed parameters here

      - name: Print new version
        run: echo "New version is ${{ steps.version.outputs.version }}"

      - name: Configure Git user
        run: |
          git config user.name "${{ secrets.BOT_NAME }}"
          git config user.email "${{ secrets.BOT_EMAIL }}"

      - name: Tag the new version
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
